{"name": "Error message for valid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Test failed:Expected to stay on login page, but redirected to dashboard\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 61, in assertion_failure\n    assert \"login\" in context.driver.current_url, \"Test failed:Expected to stay on login page, but redirected to dashboard\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1751526393273, "stop": 1751526396032}, {"name": "When I enter a valid username and password", "status": "passed", "start": 1751526396033, "stop": 1751526397300}, {"name": "Then I should see an error message instead of dashboard", "status": "failed", "statusDetails": {"message": "AssertionError: Test failed:Expected to stay on login page, but redirected to dashboard\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 61, in assertion_failure\n    assert \"login\" in context.driver.current_url, \"Test failed:Expected to stay on login page, but redirected to dashboard\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1751526397301, "stop": 1751526397305}], "start": 1751526393273, "stop": 1751526397306, "uuid": "ba6f1980-af10-42d0-a7c6-5c8febf48115", "historyId": "db53cb05f4b9b6667ff3107790fc599c", "fullName": "Login functionality of ZEN portal: Error message for valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login functionality of ZEN portal"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}